### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by jordie23**
This PR updates react-truncate to React 16.

It updates refs to be functions instead of text. 

It wraps `{text}` inside a span to fix error thrown when re-rendering (e.g. triggered by resizing)

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

The update to React 16 required updating other dependencies, which requires updating some of the tests.

Tests have also been updated to work with the new <span> tag.

Feel free to comment or add commits.

### CODE REVIEW

**Comment by jordie23** [comment]
Just realized this actually makes React 16 a required peer-dependency, when you probably still want to support react 15. I will reduce it to 15 and make sure it's working for both 15 and 16.

**Comment by jordie23** [comment]
Ok, so I _didn't_ make it a requirement, just a maximum, which should be fine. So no code change needed for that.

I just checked the module with react 15.6 and it's working.

**Comment by jordie23** [comment]
Should help https://github.com/One-com/react-truncate/issues/63

**Comment by jordie23** [comment]
And https://github.com/One-com/react-truncate/issues/62

**Comment by PabloSichert** [comment]
Not much to say - pretty damn awesome PR!

I created a new PR (#65) where I squashed / amended your commits to only contain the very essential parts.

Especially see https://github.com/One-com/react-truncate/pull/65/commits/2b5dcd23e6ff5064936e56fbca7ee72b53e21a25 and https://github.com/One-com/react-truncate/pull/65/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35

Thanks a ton, man 💯

**Pull request closed without merging**
