### PR TITLE
add window to cancelAnimationFrame and requestAnimationFrame to make them testable using sinon

### PR DESCRIPTION
**Pull request by rayvafa**
Also mentioning `window` when calling global functions and variables makes code easier to read

### CODE REVIEW

**Comment by rayvafa** [comment]
@PabloSichert I appreciate if we could push this small change out as we need it to write some unit tests in our end. thanks.

**Comment by PabloSichert** [comment]
Hi @rayvafa, just published the changes with [v2.1.5](https://github.com/One-com/react-truncate/releases/tag/v2.1.5).

**Comment by PabloSichert** [comment]
(See https://github.com/One-com/react-truncate/commit/b6cca7c8e3f7b643654ced9cb1bf80c979fd21cc)

**Comment by rayvafa** [comment]
thanks mate, I appreciate it 👍

**Pull request closed without merging**
