### PR TITLE
update on componentDidUpdate

### PR DESCRIPTION
**Pull request by TymchenkoOleksandr**
component does not updates when props.children changes until resize

### CODE REVIEW

**Comment by PabloSichert** [comment]
When you change the `children` object reference passed in to the component, it will re-render anyway, which will [invoke](https://github.com/One-com/react-truncate/blob/master/src/Truncate.js#L198) the `getLines` function inside the `render` method.

Note: `Truncate` will not re-render, when its children receive new props or re-render for whichever reason.

Did the changes you propose fix your scenario?
Would it be possible that you paste some relevant code of your usage, so I can reproduce it?

**Comment by TymchenkoOleksandr** [comment]
Truncate does not re-render sometimes on changed children object reference passed in to the component util resize
jul-21-2016 13-00-31

**Comment by PabloSichert** [comment]
What does your `about` variable contain? A plain string or a React component?

**Comment by TymchenkoOleksandr** [comment]
plain string

**Pull request closed without merging**
