### PR TITLE
Fix PropTypes deprecation warnings

### PR DESCRIPTION
**Pull request by koox00**
PropTypes are becoming deprecated in React v16.0.0 and are hitting warnings in React v15.5.0, [migration guide](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes).

### CODE REVIEW

**Comment by PabloSichert** [comment]
Thanks! Merged with 338707b...fb0b68b.

**Comment by Calyhre** [comment]
Nice! When can we expect this fix to be published?

**Comment by Calyhre** [comment]
Well, that was fast 😄  Thanks!

**Comment by PabloSichert** [comment]
Forgot to release and publish - now out with [`2.1.1`](https://github.com/One-com/react-truncate/releases/tag/v2.1.1).

**Pull request closed without merging**
